version: "3.8"
volumes:
  volume:
    name: volume
services:
  db:
    image: postgres:14
    environment:
      - "POSTGRES_PASSWORD=postgres"
      - "POSTGRES_USER=postgres"
    ports:
      - "5432:5432"
    volumes:
      - volume:/var/lib/postgresql/data